version: '3'
services:
    react:
        build:
            context: react
            dockerfile: Dockerfile
        ports:
            - "80:3000"
        volumes: ['./react/src:/app/src']
        entrypoint:
            - npm
            - start
        networks: 
            - temp_network
    flask:
        build:
            context: python
            dockerfile: Dockerfile
        volumes: ['./python/main.py:/app/main.py']
        environment:
            - FLASK_APP=/main.py
        entrypoint:
            - python
            - main.py
        networks: 
            temp_network:
    flask1:
        build:
            context: python
            dockerfile: Dockerfile
        volumes: ['./python/main.py:/app/main.py']
        environment:
            - FLASK_APP=/main.py
        entrypoint:
            - python
            - main.py
        networks: 
            temp_network:
    nginx:
        image: nginx:1.13.7-alpine
        container_name: nginx
        depends_on:
            - flask
            - flask1
        networks: 
            temp_network:
        ports:
            - 90:90
        volumes: ['./nginx/nginx.conf:/etc/nginx/nginx.conf']
networks:
  temp_network: