version: '3'
services:
    react:
        build:
            context: react
            dockerfile: Dockerfile
        ports:
            - "80:3000"
        volumes: ['./react/:/app']
        entrypoint:
            - npm
            - start
        networks: 
            - temp_network
    flask:
        build:
            context: python
            dockerfile: Dockerfile
        ports:
            - "1800:1800"
        volumes: ['./python/cnn.py:/app/cnn.py']
        environment:
            - FLASK_DEBUG=1
        entrypoint:
            - python
            - cnn.py
        networks: 
            - temp_network    
networks:
  temp_network:
